### ISSUE TITLE
No module named resources

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [rkistner/chinese-postman#7] opened 2015-11-25 23:58 UTC
Under Linux Mint/Ubuntu, I can't install due to this error already mentioned in the icon issue.
What python package might this be? Would be nice to mention that in the docs, cause obviously its something not installed by default.

**Comment by rkistner** [comment] 2015-11-26 10:53
Duplicate of #6.

**Closed by rkistner** 2015-11-26 10:53 UTC
